# Generated by Django 5.2.2 on 2025-06-10 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pizza", "0002_pizza_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="total_price",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
