# Generated by Django 5.2.2 on 2025-06-10 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pizza", "0004_ingridient_pizza_ingredients"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Ingridient",
            new_name="Ingredient",
        ),
    ]
