# Generated by Django 5.2.2 on 2025-06-10 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pizza", "0006_remove_pizza_description_remove_pizza_ingredients_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="total_price",
            field=models.DecimalField(
                decimal_places=2, default=0.0, max_digits=10, null=True
            ),
        ),
    ]
