# Generated by Django 5.2.2 on 2025-06-11 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pizza", "0007_alter_order_total_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="pizza",
            name="ingredient",
            field=models.ManyToManyField(blank=True, to="pizza.ingredient"),
        ),
    ]
