# Generated by Django 5.2.2 on 2025-06-11 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pizza", "0008_pizza_ingredient"),
    ]

    operations = [
        migrations.AddField(
            model_name="pizza",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
