# Generated by Django 5.2.2 on 2025-06-11 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pizza", "0009_pizza_description"),
    ]

    operations = [
        migrations.RenameField(
            model_name="pizza",
            old_name="ingredient",
            new_name="ingredients",
        ),
    ]
